[package]
name = "gambit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0

[profile.dev.package.'*']
opt-level = 3

[dependencies]
bevy = { version = "0.9", features = ["filesystem_watcher", "flac"] }
# bevy = { version = "0.8", features = ["dynamic"] }
bevy_egui = "0.19"
bevy_startup_tree = "0.1.1"
bevy-inspector-egui = { version = "0.17", optional = true }
chess = "3.2"
clap = { version = "4.1", features = ["derive", "wrap_help"] }
egui_extras = "0.20"
grid = "0.9"
